<?php
defined('TYPO3_MODE') or die();

/* * *************************************************************
 *  Copyright notice
 *
 *  (c) 2021 Regis TEDONE <regis.tedone@gmail.com>, SYRADEV
 *  All rights reserved
 *
 *  This script is part of the TYPO3 project. The TYPO3 project is
 *  free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  The GNU General Public License can be found at
 *  http://www.gnu.org/copyleft/gpl.html.
 *  A copy is found in the textfile GPL.txt and important notices to the license
 *  from the author is found in LICENSE.txt distributed with these scripts.
 *
 *
 *  This script is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  This copyright notice MUST APPEAR in all copies of the script!
 * ************************************************************* */

/*******************************************/
/******** Override Page Tree Icons ********/
/*****************************************/

use SYRADEV\RtPagesTreeIcons\Utility\RtBackendUtility;

$langFile = 'LLL:EXT:rt_pages_tree_icons/Resources/Private/Language/locallang.xlf:';

$pageIcons = [

	['Folder Shop',                     'shop',                 'apps-pagetree-folder-contains-shop',               'svg','default'],
	['Folder Approve',                  'approve',              'apps-pagetree-folder-contains-approve',            'svg','default'],
	['Folder Board',                    'board',                'apps-pagetree-folder-contains-board',              'svg','default'],

	[$langFile . 'pageb',               'pageb',                'apps-pagetree-page-black',                         'svg','page'],
	[$langFile . 'pageb',               'pageb-s',              'apps-pagetree-page-black-s',                       'svg','page'],
	[$langFile . 'pageb',               'pageb-h',              'apps-pagetree-page-black-h',                       'svg','page'],
	[$langFile . 'pagem',               'pagem',                'apps-pagetree-page-brown',                         'svg','page'],
	[$langFile . 'pagem',               'pagem-s',              'apps-pagetree-page-brown-s',                       'svg','page'],
	[$langFile . 'pagem',               'pagem-h',              'apps-pagetree-page-brown-h',                       'svg','page'],
	[$langFile . 'pageblt',             'pageblt',              'apps-pagetree-page-blue-light',                    'svg','page'],
	[$langFile . 'pageblt',             'pageblt-s',            'apps-pagetree-page-blue-light-s',                  'svg','page'],
	[$langFile . 'pageblt',             'pageblt-h',            'apps-pagetree-page-blue-light-h',                  'svg','page'],
	[$langFile . 'pagebl',              'pagebl',               'apps-pagetree-page-blue',                          'svg','page'],
	[$langFile . 'pagebl',              'pagebl-s',             'apps-pagetree-page-blue-s',                        'svg','page'],
	[$langFile . 'pagebl',              'pagebl-h',             'apps-pagetree-page-blue-h',                        'svg','page'],
	[$langFile . 'pageblf',             'pageblf',              'apps-pagetree-page-blue-fluo',                     'svg','page'],
	[$langFile . 'pageblf',             'pageblf-s',            'apps-pagetree-page-blue-fluo-s',                   'svg','page'],
	[$langFile . 'pageblf',             'pageblf-h',            'apps-pagetree-page-blue-fluo-h',                   'svg','page'],
	[$langFile . 'pagegb',              'pagegb',               'apps-pagetree-page-gray-brighter',                 'svg','page'],
	[$langFile . 'pagegb',              'pagegb-s',             'apps-pagetree-page-gray-brighter-s',               'svg','page'],
	[$langFile . 'pagegb',              'pagegb-h',             'apps-pagetree-page-gray-brighter-h',               'svg','page'],
	[$langFile . 'pagegd',              'pagegd',               'apps-pagetree-page-gray-dark',                     'svg','page'],
	[$langFile . 'pagegd',              'pagegd-s',             'apps-pagetree-page-gray-dark-s',                   'svg','page'],
	[$langFile . 'pagegd',              'pagegd-h',             'apps-pagetree-page-gray-dark-h',                   'svg','page'],
	[$langFile . 'pagegl',              'pagegl',               'apps-pagetree-page-gray-light',                    'svg','page'],
	[$langFile . 'pagegl',              'pagegl-s',             'apps-pagetree-page-gray-light-s',                  'svg','page'],
	[$langFile . 'pagegl',              'pagegl-h',             'apps-pagetree-page-gray-light-h',                  'svg','page'],
	[$langFile . 'pageg',               'pageg',                'apps-pagetree-page-gray',                          'svg','page'],
	[$langFile . 'pageg',               'pageg-s',              'apps-pagetree-page-gray-s',                        'svg','page'],
	[$langFile . 'pageg',               'pageg-h',              'apps-pagetree-page-gray-h',                        'svg','page'],
	[$langFile . 'pagegrl',             'pagegrl',              'apps-pagetree-page-green-light',                   'svg','page'],
	[$langFile . 'pagegrl',             'pagegrl-s',            'apps-pagetree-page-green-light-s',                 'svg','page'],
	[$langFile . 'pagegrl',             'pagegrl-h',            'apps-pagetree-page-green-light-h',                 'svg','page'],
	[$langFile . 'pagegr',              'pagegr',               'apps-pagetree-page-green',                         'svg','page'],
	[$langFile . 'pagegr',              'pagegr-s',             'apps-pagetree-page-green-s',                       'svg','page'],
	[$langFile . 'pagegr',              'pagegr-h',             'apps-pagetree-page-green-h',                       'svg','page'],
	[$langFile . 'pagegrf',             'pagegrf',              'apps-pagetree-page-green-fluo',                    'svg','page'],
	[$langFile . 'pagegrf',             'pagegrf-s',            'apps-pagetree-page-green-fluo-s',                  'svg','page'],
	[$langFile . 'pagegrf',             'pagegrf-h',            'apps-pagetree-page-green-fluo-h',                  'svg','page'],
	[$langFile . 'pageo',               'pageo',                'apps-pagetree-page-orange',                        'svg','page'],
	[$langFile . 'pageo',               'pageo-s',              'apps-pagetree-page-orange-s',                      'svg','page'],
	[$langFile . 'pageo',               'pageo-h',              'apps-pagetree-page-orange-h',                      'svg','page'],
	[$langFile . 'pageof',              'pageof',               'apps-pagetree-page-orange-fluo',                   'svg','page'],
	[$langFile . 'pageof',              'pageof-s',             'apps-pagetree-page-orange-fluo-s',                 'svg','page'],
	[$langFile . 'pageof',              'pageof-h',             'apps-pagetree-page-orange-fluo-h',                 'svg','page'],
	[$langFile . 'pagep',               'pagep',                'apps-pagetree-page-purple',                        'svg','page'],
	[$langFile . 'pagep',               'pagep-s',              'apps-pagetree-page-purple-s',                      'svg','page'],
	[$langFile . 'pagep',               'pagep-h',              'apps-pagetree-page-purple-h',                      'svg','page'],
	[$langFile . 'pagef',               'pagef',                'apps-pagetree-page-fuchsia',                       'svg','page'],
	[$langFile . 'pagef',               'pagef-s',              'apps-pagetree-page-fuchsia-s',                     'svg','page'],
	[$langFile . 'pagef',               'pagef-h',              'apps-pagetree-page-fuchsia-h',                     'svg','page'],
	[$langFile . 'pagerl',              'pagerl',               'apps-pagetree-page-red-light',                     'svg','page'],
	[$langFile . 'pagerl',              'pagerl-s',             'apps-pagetree-page-red-light-s',                   'svg','page'],
	[$langFile . 'pagerl',              'pagerl-h',             'apps-pagetree-page-red-light-h',                   'svg','page'],
	[$langFile . 'pager',               'pager',                'apps-pagetree-page-red',                           'svg','page'],
	[$langFile . 'pager',               'pager-s',              'apps-pagetree-page-red-s',                         'svg','page'],
	[$langFile . 'pager',               'pager-h',              'apps-pagetree-page-red-h',                         'svg','page'],
	[$langFile . 'pagerf',              'pagerf',               'apps-pagetree-page-red-fluo',                      'svg','page'],
	[$langFile . 'pagerf',              'pagerf-s',             'apps-pagetree-page-red-fluo-s',                    'svg','page'],
	[$langFile . 'pagerf',              'pagerf-h',             'apps-pagetree-page-red-fluo-h',                    'svg','page'],
	[$langFile . 'pagew',               'pagew',                'apps-pagetree-page-white',                         'svg','page'],
	[$langFile . 'pagew',               'pagew-s',              'apps-pagetree-page-white-s',                       'svg','page'],
	[$langFile . 'pagew',               'pagew-h',              'apps-pagetree-page-white-h',                       'svg','page'],
	[$langFile . 'pageyl',              'pageyl',               'apps-pagetree-page-yellow-light',                  'svg','page'],
	[$langFile . 'pageyl',              'pageyl-s',             'apps-pagetree-page-yellow-light-s',                'svg','page'],
	[$langFile . 'pageyl',              'pageyl-h',             'apps-pagetree-page-yellow-light-h',                'svg','page'],
	[$langFile . 'pagey',               'pagey',                'apps-pagetree-page-yellow',                        'svg','page'],
	[$langFile . 'pagey',               'pagey-s',              'apps-pagetree-page-yellow-s',                      'svg','page'],
	[$langFile . 'pagey',               'pagey-h',              'apps-pagetree-page-yellow-h',                      'svg','page'],
	[$langFile . 'pageyf',              'pageyf',               'apps-pagetree-page-yellow-fluo',                   'svg','page'],
	[$langFile . 'pageyf',              'pageyf-s',             'apps-pagetree-page-yellow-fluo-s',                 'svg','page'],
	[$langFile . 'pageyf',              'pageyf-h',             'apps-pagetree-page-yellow-fluo-h',                 'svg','page'],
	[$langFile . 'pagegdpr',            'pagegdpr',             'apps-pagetree-page-gdpr',                          'svg','page'],
	[$langFile . 'pagegdpr',            'pagegdpr-s',           'apps-pagetree-page-gdpr-s',                        'svg','page'],
	[$langFile . 'pagegdpr',            'pagegdpr-h',           'apps-pagetree-page-gdpr-h',                        'svg','page'],

	[$langFile . 'folderb',             'folderb',              'apps-pagetree-filetree-folder-black',              'svg','folder'],
	[$langFile . 'folderm',             'folderm',              'apps-pagetree-filetree-folder-brown',              'svg','folder'],
	[$langFile . 'folderblt',           'folderblt',            'apps-pagetree-filetree-folder-blue-light',         'svg','folder'],
	[$langFile . 'folderbl',            'folderbl',             'apps-pagetree-filetree-folder-blue',               'svg','folder'],
	[$langFile . 'folderblf',           'folderblf',            'apps-pagetree-filetree-folder-blue-fluo',          'svg','folder'],
	[$langFile . 'foldergb',            'foldergb',             'apps-pagetree-filetree-folder-gray-brighter',      'svg','folder'],
	[$langFile . 'foldergd',            'foldergd',             'apps-pagetree-filetree-folder-gray-dark',          'svg','folder'],
	[$langFile . 'foldergl',            'foldergl',             'apps-pagetree-filetree-folder-gray-light',         'svg','folder'],
	[$langFile . 'folderg',             'folderg',              'apps-pagetree-filetree-folder-gray',               'svg','folder'],
	[$langFile . 'foldergrl',           'foldergrl',            'apps-pagetree-filetree-folder-green-light',        'svg','folder'],
	[$langFile . 'foldergr',            'foldergr',             'apps-pagetree-filetree-folder-green',              'svg','folder'],
	[$langFile . 'foldergrf',           'foldergrf',            'apps-pagetree-filetree-folder-green-fluo',         'svg','folder'],
	[$langFile . 'foldero',             'foldero',              'apps-pagetree-filetree-folder-orange',             'svg','folder'],
	[$langFile . 'folderof',            'folderof',             'apps-pagetree-filetree-folder-orange-fluo',        'svg','folder'],
	[$langFile . 'folderp',             'folderp',              'apps-pagetree-filetree-folder-purple',             'svg','folder'],
	[$langFile . 'folderf',             'folderf',              'apps-pagetree-filetree-folder-fuchsia',            'svg','folder'],
	[$langFile . 'folderrl',            'folderrl',             'apps-pagetree-filetree-folder-red-light',          'svg','folder'],
	[$langFile . 'folderr',             'folderr',              'apps-pagetree-filetree-folder-red',                'svg','folder'],
	[$langFile . 'folderrf',            'folderrf',             'apps-pagetree-filetree-folder-red-fluo',           'svg','folder'],
	[$langFile . 'folderw',             'folderw',              'apps-pagetree-filetree-folder-white',              'svg','folder'],
	[$langFile . 'folderyl',            'folderyl',             'apps-pagetree-filetree-folder-yellow-light',       'svg','folder'],
	[$langFile . 'foldery',             'foldery',              'apps-pagetree-filetree-folder-yellow',             'svg','folder'],
	[$langFile . 'folderyf',            'folderyf',             'apps-pagetree-filetree-folder-yellow-fluo',        'svg','folder'],

	[$langFile . 'rfolderb',            'rfolderb',             'apps-pagetree-rounded-folder-black',               'svg','folder'],
	[$langFile . 'rfolderm',            'rfolderm',             'apps-pagetree-rounded-folder-brown',               'svg','folder'],
	[$langFile . 'rfolderblt',          'rfolderblt',           'apps-pagetree-rounded-folder-blue-light',          'svg','folder'],
	[$langFile . 'rfolderbl',           'rfolderbl',            'apps-pagetree-rounded-folder-blue',                'svg','folder'],
	[$langFile . 'rfolderblf',          'rfolderblf',           'apps-pagetree-rounded-folder-blue-fluo',           'svg','folder'],
	[$langFile . 'rfoldergb',           'rfoldergb',            'apps-pagetree-rounded-folder-gray-brighter',       'svg','folder'],
	[$langFile . 'rfoldergd',           'rfoldergd',            'apps-pagetree-rounded-folder-gray-dark',           'svg','folder'],
	[$langFile . 'rfoldergl',           'rfoldergl',            'apps-pagetree-rounded-folder-gray-light',          'svg','folder'],
	[$langFile . 'rfolderg',            'rfolderg',             'apps-pagetree-rounded-folder-gray',                'svg','folder'],
	[$langFile . 'rfoldergrl',          'rfoldergrl',           'apps-pagetree-rounded-folder-green-light',         'svg','folder'],
	[$langFile . 'rfoldergr',           'rfoldergr',            'apps-pagetree-rounded-folder-green',               'svg','folder'],
	[$langFile . 'rfoldergrf',          'rfoldergrf',           'apps-pagetree-rounded-folder-green-fluo',          'svg','folder'],
	[$langFile . 'rfoldero',            'rfoldero',             'apps-pagetree-rounded-folder-orange',              'svg','folder'],
	[$langFile . 'rfolderof',           'rfolderof',            'apps-pagetree-rounded-folder-orange-fluo',         'svg','folder'],
	[$langFile . 'rfolderp',            'rfolderp',             'apps-pagetree-rounded-folder-purple',              'svg','folder'],
	[$langFile . 'rfolderf',            'rfolderf',             'apps-pagetree-rounded-folder-fuchsia',              'svg','folder'],
	[$langFile . 'rfolderrl',           'rfolderrl',            'apps-pagetree-rounded-folder-red-light',           'svg','folder'],
	[$langFile . 'rfolderr',            'rfolderr',             'apps-pagetree-rounded-folder-red',                 'svg','folder'],
	[$langFile . 'rfolderrf',           'rfolderrf',            'apps-pagetree-rounded-folder-red-fluo',            'svg','folder'],
	[$langFile . 'rfolderw',            'rfolderw',             'apps-pagetree-rounded-folder-white',               'svg','folder'],
	[$langFile . 'rfolderyl',           'rfolderyl',            'apps-pagetree-rounded-folder-yellow-light',        'svg','folder'],
	[$langFile . 'rfoldery',            'rfoldery',             'apps-pagetree-rounded-folder-yellow',              'svg','folder'],
	[$langFile . 'rfolderyf',           'rfolderyf',            'apps-pagetree-rounded-folder-yellow-fluo',         'svg','folder'],

	[$langFile . 'symbcoconut',         'symbcocotier',         'actions-pagetree-change-page-icon',                'svg','symbol'],
	[$langFile . 'symbcoconut',         'symbcocotier-h',       'actions-pagetree-change-page-icon-h',              'svg','symbol'],
	[$langFile . 'symbshortcut',        'symbshortcut',         'apps-pagetree-shortcut',                           'svg','symbol'],
	[$langFile . 'symbshortcut',        'symbshortcut-h',       'apps-pagetree-shortcut-h',                         'svg','symbol'],
	[$langFile . 'symblandpage',        'symblandpage',         'apps-pagetree-landing-page',                       'svg','symbol'],
	[$langFile . 'symblandpage',        'symblandpage-h',       'apps-pagetree-landing-page-h',                     'svg','symbol'],
	[$langFile . 'apppresentation',     'apppresentation',      'apps-pagetree-presentation',                       'svg','symbol'],
	[$langFile . 'apppresentation',     'apppresentation-h',    'apps-pagetree-presentation-h',                     'svg','symbol'],
	[$langFile . 'symbdownload',        'symbdownload',         'apps-pagetree-download',                           'svg','symbol'],
	[$langFile . 'symbdownload',        'symbdownload-h',       'apps-pagetree-download-h',                         'svg','symbol'],
	[$langFile . 'symbform',            'symbform',             'apps-pagetree-form',                               'svg','symbol'],
	[$langFile . 'symbform',            'symbform-h',           'apps-pagetree-form-h',                             'svg','symbol'],
	[$langFile . 'symbdesktop',         'symbdesktop',          'apps-pagetree-ux-desktop',                         'svg','symbol'],
	[$langFile . 'symbdesktop',         'symbdesktop-h',        'apps-pagetree-ux-desktop-h',                       'svg','symbol'],
	[$langFile . 'symbtablet',          'symbtablet',           'apps-pagetree-ux-tablet',                          'svg','symbol'],
	[$langFile . 'symbtablet',          'symbtablet-h',         'apps-pagetree-ux-tablet-h',                        'svg','symbol'],
	[$langFile . 'symbmobile',          'symbmobile',           'apps-pagetree-ux-mobile',                          'svg','symbol'],
	[$langFile . 'symbmobile',          'symbmobile-h',         'apps-pagetree-ux-mobile-h',                        'svg','symbol'],
	[$langFile . 'symbhome',            'symbhome',             'apps-pagetree-home',                               'svg','symbol'],
	[$langFile . 'symbhome',            'symbhome-h',           'apps-pagetree-home-h',                             'svg','symbol'],
	[$langFile . 'symbvideo',           'symbvideo',            'apps-pagetree-video',                              'svg','symbol'],
	[$langFile . 'symbvideo',           'symbvideo-h',          'apps-pagetree-video-h',                            'svg','symbol'],
	[$langFile . 'symbaudio',           'symbaudio',            'apps-pagetree-audio',                              'svg','symbol'],
	[$langFile . 'symbaudio',           'symbaudio-h',          'apps-pagetree-audio-h',                            'svg','symbol'],
	[$langFile . 'symbcamera',          'symbcamera',           'apps-pagetree-camera',                             'svg','symbol'],
	[$langFile . 'symbcamera',          'symbcamera-h',         'apps-pagetree-camera-h',                           'svg','symbol'],
	[$langFile . 'symbimage',           'symbcimage',           'apps-pagetree-image',                              'svg','symbol'],
	[$langFile . 'symbimage',           'symbcimage-h',         'apps-pagetree-image-h',                            'svg','symbol'],
	[$langFile . 'symbcomments',        'symbcomments',         'apps-pagetree-comments',                           'svg','symbol'],
	[$langFile . 'symbcomments',        'symbcomments-h',       'apps-pagetree-comments-h',                         'svg','symbol'],
	[$langFile . 'symbmagnifier',       'symbmagnifier',        'apps-pagetree-magnifier',                          'svg','symbol'],
	[$langFile . 'symbmagnifier',       'symbmagnifier-h',      'apps-pagetree-magnifier-h',                        'svg','symbol'],
	[$langFile . 'symbmail',            'symbmail',             'apps-pagetree-mail',                               'svg','symbol'],
	[$langFile . 'symbmail',            'symbmail-h',           'apps-pagetree-mail-h',                             'svg','symbol'],
	[$langFile . 'symbbooks',           'symbbooks',            'apps-pagetree-books',                              'svg','symbol'],
	[$langFile . 'symbbooks',           'symbbooks-h',          'apps-pagetree-books-h',                            'svg','symbol'],
	[$langFile . 'symbjobs',            'symbjobs',             'apps-pagetree-jobs',                               'svg','symbol'],
	[$langFile . 'symbjobs',            'symbjobs-h',           'apps-pagetree-jobs-h',                             'svg','symbol'],
	[$langFile . 'symblegalnotice',     'symblegalnotice',      'apps-pagetree-legal-notice',                       'svg','symbol'],
	[$langFile . 'symblegalnotice',     'symblegalnotice-h',    'apps-pagetree-legal-notice-h',                     'svg','symbol'],
	[$langFile . 'symbsitemap',         'symbsitemap',          'apps-pagetree-sitemap',                            'svg','symbol'],
	[$langFile . 'symbsitemap',         'symbsitemap-h',        'apps-pagetree-sitemap-h',                          'svg','symbol'],
	[$langFile . 'symbmenu',            'symbmenu',             'apps-pagetree-menu',                               'svg','symbol'],
	[$langFile . 'symbmenu',            'symbmenu-h',           'apps-pagetree-menu-h',                             'svg','symbol'],
	[$langFile . 'symbagenda',          'symbagenda',           'apps-pagetree-agenda',                             'svg','symbol'],
	[$langFile . 'symbagenda',          'symbagenda-h',         'apps-pagetree-agenda-h',                           'svg','symbol'],
	[$langFile . 'symbphone',           'symbphone',            'apps-pagetree-phone',                              'svg','symbol'],
	[$langFile . 'symbphone',           'symbphone-h',          'apps-pagetree-phone-h',                            'svg','symbol'],
	[$langFile . 'symblocation',        'symblocation',         'apps-pagetree-location',                           'svg','symbol'],
	[$langFile . 'symblocation',        'symblocation-h',       'apps-pagetree-location-h',                         'svg','symbol'],
	[$langFile . 'symbcloud',           'symbcloud',            'apps-pagetree-cloud',                              'svg','symbol'],
	[$langFile . 'symbcloud',           'symbcloud-h',          'apps-pagetree-cloud-h',                            'svg','symbol'],
	[$langFile . 'symbmeteo',           'symbmeteo',            'apps-pagetree-meteo',                              'svg','symbol'],
	[$langFile . 'symbmeteo',           'symbmeteo-h',          'apps-pagetree-meteo-h',                            'svg','symbol'],
	[$langFile . 'symbcredcard',        'symbcredcard',         'apps-pagetree-credit-card',                        'svg','symbol'],
	[$langFile . 'symbcredcard',        'symbcredcard-h',       'apps-pagetree-credit-card-h',                      'svg','symbol'],
	[$langFile . 'symbshopcart',        'symbshopcart',         'apps-pagetree-shopping-cart',                      'svg','symbol'],
	[$langFile . 'symbshopcart',        'symbshopcart-h',       'apps-pagetree-shopping-cart-h',                    'svg','symbol'],
	[$langFile . 'symbuniversity',      'symbuniversity',       'apps-pagetree-university',                         'svg','symbol'],
	[$langFile . 'symbuniversity',      'symbuniversity-h',     'apps-pagetree-university-h',                       'svg','symbol'],
	[$langFile . 'symbbrainstorm',      'symbbrainstorm',       'apps-pagetree-brainstorm',                         'svg','symbol'],
	[$langFile . 'symbbrainstorm',      'symbbrainstorm-h',     'apps-pagetree-brainstorm-h',                       'svg','symbol'],
	[$langFile . 'symbfaq',             'symbfaq',              'apps-pagetree-faq',                                'svg','symbol'],
	[$langFile . 'symbfaq',             'symbfaq-h',            'apps-pagetree-faq-h',                              'svg','symbol'],
	[$langFile . 'symbtestimonial',     'symbtestimonial',      'apps-pagetree-testimonial',                        'svg','symbol'],
	[$langFile . 'symbtestimonial',     'symbtestimonial-h',    'apps-pagetree-testimonial-h',                      'svg','symbol'],
	[$langFile . 'symbannouncement',    'symbannouncement',     'apps-pagetree-announcement',                       'svg','symbol'],
	[$langFile . 'symbannouncement',    'symbannouncement-h',   'apps-pagetree-announcement-h',                     'svg','symbol'],
	[$langFile . 'symbchart',           'symbchart',            'apps-pagetree-chart',                              'svg','symbol'],
	[$langFile . 'symbchart',           'symbchart-h',          'apps-pagetree-chart-h',                            'svg','symbol'],
	[$langFile . 'symbarob',            'symbarob',             'apps-pagetree-arobase-black',                      'svg','symbol'],
	[$langFile . 'symbarob',            'symbarob-h',           'apps-pagetree-arobase-black-h',                    'svg','symbol'],
	[$langFile . 'symbaroo',            'symbaroo',             'apps-pagetree-arobase-orange',                     'svg','symbol'],
	[$langFile . 'symbaroo',            'symbaroo-h',           'apps-pagetree-arobase-orange-h',                   'svg','symbol'],
	[$langFile . 'symbastb',            'symbastb',             'apps-pagetree-asterisk-black',                     'svg','symbol'],
	[$langFile . 'symbastb',            'symbastb-h',           'apps-pagetree-asterisk-black-h',                   'svg','symbol'],
	[$langFile . 'symbasto',            'symbasto',             'apps-pagetree-asterisk-orange',                    'svg','symbol'],
	[$langFile . 'symbasto',            'symbasto-h',           'apps-pagetree-asterisk-orange-h',                  'svg','symbol'],
	[$langFile . 'symbhtagb',           'symbhtagb',            'apps-pagetree-hashtag-black',                      'svg','symbol'],
	[$langFile . 'symbhtagb',           'symbhtagb-h',          'apps-pagetree-hashtag-black-h',                    'svg','symbol'],
	[$langFile . 'symbhtago',           'symbhtago',            'apps-pagetree-hashtag-orange',                     'svg','symbol'],
	[$langFile . 'symbhtago',           'symbhtago-h',          'apps-pagetree-hashtag-orange-h',                   'svg','symbol'],
	[$langFile . 'symbgearb',           'symbgearb',            'apps-pagetree-gear-black',                         'svg','symbol'],
	[$langFile . 'symbgearb',           'symbgearb-h',          'apps-pagetree-gear-black-h',                       'svg','symbol'],
	[$langFile . 'symbgearo',           'symbgearo',            'apps-pagetree-gear-orange',                        'svg','symbol'],
	[$langFile . 'symbgearo',           'symbgearo-h',          'apps-pagetree-gear-orange-h',                      'svg','symbol'],
	[$langFile . 'symbstarb',           'symbstarb',            'apps-pagetree-star-black',                         'svg','symbol'],
	[$langFile . 'symbstarb',           'symbstarb-h',          'apps-pagetree-star-black-h',                       'svg','symbol'],
	[$langFile . 'symbstaro',           'symbstaro',            'apps-pagetree-star-orange',                        'svg','symbol'],
	[$langFile . 'symbstaro',           'symbstaro-h',          'apps-pagetree-star-orange-h',                      'svg','symbol'],
	[$langFile . 'symbwrenchb',         'symbwrenchb',          'apps-pagetree-wrench-black',                       'svg','symbol'],
	[$langFile . 'symbwrenchb',         'symbwrenchb-h',        'apps-pagetree-wrench-black-h',                     'svg','symbol'],
	[$langFile . 'symbwrencho',         'symbwrencho',          'apps-pagetree-wrench-orange',                      'svg','symbol'],
	[$langFile . 'symbwrencho',         'symbwrencho-h',        'apps-pagetree-wrench-orange-h',                    'svg','symbol'],
	[$langFile . 'symbcube',            'symbcube',             'apps-pagetree-cube',                               'svg','symbol'],
	[$langFile . 'symbcube',            'symbcube-h',           'apps-pagetree-cube-h',                             'svg','symbol'],
	[$langFile . 'symbproduct',         'symbproduct',          'apps-pagetree-product',                            'svg','symbol'],
	[$langFile . 'symbproduct',         'symbproduct-h',        'apps-pagetree-product-h',                          'svg','symbol'],
	[$langFile . 'symbdelivery',        'symbdelivery',         'apps-pagetree-delivery',                           'svg','symbol'],
	[$langFile . 'symbdelivery',        'symbdelivery-h',       'apps-pagetree-delivery-h',                         'svg','symbol'],
	[$langFile . 'symbgift',            'symbgift',             'apps-pagetree-gift',                               'svg','symbol'],
	[$langFile . 'symbgift',            'symbgift-h',           'apps-pagetree-gift-h',                             'svg','symbol'],
	[$langFile . 'symbheartb',          'symbheartb',           'apps-pagetree-heart-b',                            'svg','symbol'],
	[$langFile . 'symbheartb',          'symbheartb-h',         'apps-pagetree-heart-b-h',                          'svg','symbol'],
	[$langFile . 'symbheartr',          'symbheartr',           'apps-pagetree-heart-r',                            'svg','symbol'],
	[$langFile . 'symbheartr',          'symbheartr-h',         'apps-pagetree-heart-r-h',                          'svg','symbol'],
	[$langFile . 'symbarchive',         'symbarchive',          'apps-pagetree-archive',                            'svg','symbol'],
	[$langFile . 'symbarchive',         'symbarchive-h',        'apps-pagetree-archive-h',                          'svg','symbol'],
	[$langFile . 'symbart',             'symbart',              'apps-pagetree-art',                                'svg','symbol'],
	[$langFile . 'symbart',             'symbart-h',            'apps-pagetree-art-h',                              'svg','symbol'],
	[$langFile . 'symbdb',              'symbdb',               'apps-pagetree-database',                           'svg','symbol'],
	[$langFile . 'symbdb',              'symbdb-h',             'apps-pagetree-database-h',                         'svg','symbol'],
	[$langFile . 'symblightbulb',       'symblightbulb',        'apps-pagetree-lightbulb',                          'svg','symbol'],
	[$langFile . 'symblightbulb',       'symblightbulb-h',      'apps-pagetree-lightbulb-h',                        'svg','symbol'],
	[$langFile . 'symblock',            'symblock',             'apps-pagetree-lock',                               'svg','symbol'],
	[$langFile . 'symblock',            'symblock-h',           'apps-pagetree-lock-h',                             'svg','symbol'],
	[$langFile . 'symbsak',             'symbsak',              'apps-pagetree-swiss-army-knife',                   'svg','symbol'],
	[$langFile . 'symbsak',             'symbsak-h',            'apps-pagetree-swiss-army-knife-h',                 'svg','symbol'],
	[$langFile . 'symbusers',           'symbusers',            'apps-pagetree-users',                              'svg','symbol'],
	[$langFile . 'symbusers',           'symbusers-h',          'apps-pagetree-users-h',                            'svg','symbol'],
	[$langFile . 'symbuser',            'symbuser',             'apps-pagetree-user',                               'svg','symbol'],
	[$langFile . 'symbuser',            'symbuser-h',           'apps-pagetree-user-h',                             'svg','symbol'],
	[$langFile . 'symbearth',           'symbearth',            'apps-pagetree-earth',                              'svg','symbol'],
	[$langFile . 'symbearth',           'symbearth-h',          'apps-pagetree-earth-h',                            'svg','symbol'],
	[$langFile . 'symbearth-s',         'symbearth-s',          'apps-pagetree-earth-s',                            'svg','symbol'],
	[$langFile . 'symbbookmark',        'symbbookmark',         'apps-pagetree-bookmark',                           'svg','symbol'],
	[$langFile . 'symbbookmark',        'symbbookmark-h',       'apps-pagetree-bookmark-h',                         'svg','symbol'],
	[$langFile . 'symblink',            'symblink',             'apps-pagetree-link',                               'svg','symbol'],
	[$langFile . 'symblink',            'symblink-h',           'apps-pagetree-link-h',                             'svg','symbol'],
	[$langFile . 'symblogin',           'symblogin',            'apps-pagetree-login',                              'svg','symbol'],
	[$langFile . 'symblogin',           'symblogin-h',          'apps-pagetree-login-h',                            'svg','symbol'],
	[$langFile . 'symblive',            'symblive',             'apps-pagetree-live',                               'svg','symbol'],
	[$langFile . 'symblive',            'symblive-h',           'apps-pagetree-live-h',                             'svg','symbol'],

	[$langFile . 'syslinux',            'appsyslinux',          'apps-pagetree-linux-black',                        'svg','app'],
	[$langFile . 'syslinux',            'appsyslinux-h',        'apps-pagetree-linux-black-h',                      'svg','app'],
	[$langFile . 'sysandroid',          'appsysandroid',        'apps-pagetree-android-black',                      'svg','app'],
	[$langFile . 'sysandroid',          'appsysandroid-h',      'apps-pagetree-android-black-h',                    'svg','app'],
	[$langFile . 'sysapple',            'appsysapple',          'apps-pagetree-apple-black',                        'svg','app'],
	[$langFile . 'sysapple',            'appsysapple-h',        'apps-pagetree-apple-black-h',                      'svg','app'],
	[$langFile . 'syswindows',          'appsyswindows',        'apps-pagetree-windows-black',                      'svg','app'],
	[$langFile . 'syswindows',          'appsyswindows-h',      'apps-pagetree-windows-black-h',                    'svg','app'],
	[$langFile . 'browserchrome',       'appbrowserchrome',     'apps-pagetree-browser-chrome',                     'svg','app'],
	[$langFile . 'browserchrome',       'appbrowserchrome-h',   'apps-pagetree-browser-chrome-h',                   'svg','app'],
	[$langFile . 'browserfirefox',      'appbrowserfirefox',    'apps-pagetree-browser-firefox',                    'svg','app'],
	[$langFile . 'browserfirefox',      'appbrowserfirefox-h',  'apps-pagetree-browser-firefox-h',                  'svg','app'],
	[$langFile . 'browseropera',        'appbrowseropera',      'apps-pagetree-browser-opera',                      'svg','app'],
	[$langFile . 'browseropera',        'appbrowseropera-h',    'apps-pagetree-browser-opera-h',                    'svg','app'],
	[$langFile . 'browsersafari',       'appbrowsersafari',     'apps-pagetree-browser-safari',                     'svg','app'],
	[$langFile . 'browsersafari',       'appbrowsersafari-h',   'apps-pagetree-browser-safari-h',                   'svg','app'],
	[$langFile . 'browseredge',         'appbrowseredge',       'apps-pagetree-browser-ie',                         'svg','app'],
	[$langFile . 'browseredge',         'appbrowseredge-h',     'apps-pagetree-browser-ie-h',                       'svg','app'],
	['HTML5',                           'apphtml5',             'apps-pagetree-html5',                              'svg','app'],
	['HTML5',                           'apphtml5-h',           'apps-pagetree-html5-h',                            'svg','app'],
	['CSS3',                            'appcss3',              'apps-pagetree-css3',                               'svg','app'],
	['CSS3',                            'appcss3-h',            'apps-pagetree-css3-h',                             'svg','app'],
	['jQuery',                          'appjquery',            'apps-pagetree-jquery',                             'svg','app'],
	['jQuery',                          'appjquery-h',          'apps-pagetree-jquery-h',                           'svg','app'],
	['Bootstrap',                       'appbootstrap',         'apps-pagetree-bootstrap',                          'svg','app'],
	['Bootstrap',                       'appbootstrap-h',       'apps-pagetree-bootstrap-h',                        'svg','app'],
	['Pdf',                             'apppdf',               'apps-pagetree-pdf',                                'svg','app'],
	['Pdf',                             'apppdf-h',             'apps-pagetree-pdf-h',                              'svg','app'],
	['Git branch',                      'appgitbranch',         'apps-pagetree-git-branch',                         'svg','app'],
	['Git branch',                      'appgitbranch-h',       'apps-pagetree-git-branch-h',                       'svg','app'],
	['Git merge',                       'appgitmerge',          'apps-pagetree-git-merge',                          'svg','app'],
	['Git merge',                       'appgitmerge-h',        'apps-pagetree-git-merge-h',                        'svg','app'],
	['PHP',                             'appphp',               'apps-pagetree-php',                                'svg','app'],
	['PHP',                             'appphp-h',             'apps-pagetree-php-h',                              'svg','app'],
	['Blogger',                         'appblogger',           'apps-pagetree-blogger',                            'svg','app'],
	['Blogger',                         'appblogger-h',         'apps-pagetree-blogger-h',                          'svg','app'],
	['Facebook',                        'appsocialfb',          'apps-pagetree-social-facebook',                    'svg','app'],
	['Facebook',                        'appsocialfb-h',        'apps-pagetree-social-facebook-h',                  'svg','app'],
	['Twitter',                         'appsocialtw',          'apps-pagetree-social-twitter',                     'svg','app'],
	['Twitter',                         'appsocialtw-h',        'apps-pagetree-social-twitter-h',                   'svg','app'],
	['Google',                          'appgoogle',            'apps-pagetree-google',                             'svg','app'],
	['Google',                          'appgoogle-h',          'apps-pagetree-google-h',                           'svg','app'],
	['LinkedIn',                        'appsocialli',          'apps-pagetree-social-linkedin',                    'svg','app'],
	['LinkedIn',                        'appsocialli-h',        'apps-pagetree-social-linkedin-h',                  'svg','app'],
	['Viadeo',                          'appsocialvi',          'apps-pagetree-social-viadeo',                      'svg','app'],
	['Viadeo',                          'appsocialvi-h',        'apps-pagetree-social-viadeo-h',                    'svg','app'],
	['Vimeo',                           'appsocialvimeo',       'apps-pagetree-social-vimeo',                       'svg','app'],
	['Vimeo',                           'appsocialvimeo-h',     'apps-pagetree-social-vimeo-h',                     'svg','app'],
	['Youtube',                         'appsocialyoutube',     'apps-pagetree-social-youtube',                     'svg','app'],
	['Youtube',                         'appsocialyoutube-h',   'apps-pagetree-social-youtube-h',                   'svg','app'],
	['Instagram',                       'appsocialinstagram',   'apps-pagetree-social-instagram',                   'svg','app'],
	['Instagram',                       'appsocialinstagram-h', 'apps-pagetree-social-instagram-h',                 'svg','app'],
	[$langFile .'apptypo3b',            'apptypo3b',            'apps-pagetree-logo-typo3-black',                   'svg','app'],
	[$langFile .'apptypo3b',            'apptypo3b-h',          'apps-pagetree-logo-typo3-black-h',                 'svg','app'],
	[$langFile .'apptypo3o',            'apptypo3o',            'apps-pagetree-logo-typo3-orange',                  'svg','app'],
	[$langFile .'apptypo3o',            'apptypo3o-h',          'apps-pagetree-logo-typo3-orange-h',                'svg','app'],
	[$langFile .'appts',                'appts',                'apps-pagetree-typoscript-orange',                  'svg','app'],
	[$langFile .'appts',                'appts-h',              'apps-pagetree-typoscript-orange-h',                'svg','app'],
	[$langFile .'appdev',               'appdev',               'apps-pagetree-dev',                                'svg','app'],
	[$langFile .'appdev-h',             'appdev-h',             'apps-pagetree-dev-h',                              'svg','app'],
	[$langFile .'app404',               'app404',               'apps-pagetree-error-404',                          'svg','app'],
	[$langFile .'app404',               'app404-h',             'apps-pagetree-error-404-h',                        'svg','app'],
	[$langFile .'apptemplates',         'apptemplates',         'apps-pagetree-templates',                          'svg','app'],
	[$langFile .'apptemplates',         'apptemplates-h',       'apps-pagetree-templates-h',                        'svg','app'],
	[$langFile .'appbelayouts',         'appbelayouts',         'apps-pagetree-backend-layout',                     'svg','app'],
	[$langFile .'appbelayouts',         'appbelayouts-h',       'apps-pagetree-backend-layout-h',                   'svg','app'],
	[$langFile .'appgride',             'appgride',             'apps-pagetree-grid-elements',                      'svg','app'],
	[$langFile .'appgride',             'appgride-h',           'apps-pagetree-grid-elements-h',                    'svg','app'],
	[$langFile .'apprssb',              'apprssb',              'apps-pagetree-rss-black',                          'svg','app'],
	[$langFile .'apprssb',              'apprssb-h',            'apps-pagetree-rss-black-h',                        'svg','app'],
	[$langFile .'apprsso',              'apprsso',              'apps-pagetree-rss-orange',                         'svg','app'],
	[$langFile .'apprsso',              'apprsso-h',            'apps-pagetree-rss-orange-h',                       'svg','app'],

	[$langFile . 'alphabeta',           'alphabeta',            'apps-pagetree-alphanum-a',                         'svg','alphanum'],
	[$langFile . 'alphabeta',           'alphabeta-h',          'apps-pagetree-alphanum-a-h',                       'svg','alphanum'],
	[$langFile . 'alphabetb',           'alphabetb',            'apps-pagetree-alphanum-b',                         'svg','alphanum'],
	[$langFile . 'alphabetb',           'alphabetb-h',          'apps-pagetree-alphanum-b-h',                       'svg','alphanum'],
	[$langFile . 'alphabetc',           'alphabetc',            'apps-pagetree-alphanum-c',                         'svg','alphanum'],
	[$langFile . 'alphabetc',           'alphabetc-h',          'apps-pagetree-alphanum-c-h',                       'svg','alphanum'],
	[$langFile . 'alphabetd',           'alphabetd',            'apps-pagetree-alphanum-d',                         'svg','alphanum'],
	[$langFile . 'alphabetd',           'alphabetd-h',          'apps-pagetree-alphanum-d-h',                       'svg','alphanum'],
	[$langFile . 'alphabete',           'alphabete',            'apps-pagetree-alphanum-e',                         'svg','alphanum'],
	[$langFile . 'alphabete',           'alphabete-h',          'apps-pagetree-alphanum-e-h',                       'svg','alphanum'],
	[$langFile . 'alphabetf',           'alphabetf',            'apps-pagetree-alphanum-f',                         'svg','alphanum'],
	[$langFile . 'alphabetf',           'alphabetf-h',          'apps-pagetree-alphanum-f-h',                       'svg','alphanum'],
	[$langFile . 'alphabetg',           'alphabetg',            'apps-pagetree-alphanum-g',                         'svg','alphanum'],
	[$langFile . 'alphabetg',           'alphabetg-h',          'apps-pagetree-alphanum-g-h',                       'svg','alphanum'],
	[$langFile . 'alphabeth',           'alphabeth',            'apps-pagetree-alphanum-h',                         'svg','alphanum'],
	[$langFile . 'alphabeth',           'alphabeth-h',          'apps-pagetree-alphanum-h-h',                       'svg','alphanum'],
	[$langFile . 'alphabeti',           'alphabeti',            'apps-pagetree-alphanum-i',                         'svg','alphanum'],
	[$langFile . 'alphabeti',           'alphabeti-h',          'apps-pagetree-alphanum-i-h',                       'svg','alphanum'],
	[$langFile . 'alphabetj',           'alphabetj',            'apps-pagetree-alphanum-j',                         'svg','alphanum'],
	[$langFile . 'alphabetj',           'alphabetj-h',          'apps-pagetree-alphanum-j-h',                       'svg','alphanum'],
	[$langFile . 'alphabetk',           'alphabetk',            'apps-pagetree-alphanum-k',                         'svg','alphanum'],
	[$langFile . 'alphabetk',           'alphabetk-h',          'apps-pagetree-alphanum-k-h',                       'svg','alphanum'],
	[$langFile . 'alphabetl',           'alphabetl',            'apps-pagetree-alphanum-l',                         'svg','alphanum'],
	[$langFile . 'alphabetl',           'alphabetl-h',          'apps-pagetree-alphanum-l-h',                       'svg','alphanum'],
	[$langFile . 'alphabetm',           'alphabetm',            'apps-pagetree-alphanum-m',                         'svg','alphanum'],
	[$langFile . 'alphabetm',           'alphabetm-h',          'apps-pagetree-alphanum-m-h',                       'svg','alphanum'],
	[$langFile . 'alphabetn',           'alphabetn',            'apps-pagetree-alphanum-n',                         'svg','alphanum'],
	[$langFile . 'alphabetn',           'alphabetn-h',          'apps-pagetree-alphanum-n-h',                       'svg','alphanum'],
	[$langFile . 'alphabeto',           'alphabeto',            'apps-pagetree-alphanum-o',                         'svg','alphanum'],
	[$langFile . 'alphabeto',           'alphabeto-h',          'apps-pagetree-alphanum-o-h',                       'svg','alphanum'],
	[$langFile . 'alphabetp',           'alphabetp',            'apps-pagetree-alphanum-p',                         'svg','alphanum'],
	[$langFile . 'alphabetp',           'alphabetp-h',          'apps-pagetree-alphanum-p-h',                       'svg','alphanum'],
	[$langFile . 'alphabetq',           'alphabetq',            'apps-pagetree-alphanum-q',                         'svg','alphanum'],
	[$langFile . 'alphabetq',           'alphabetq-h',          'apps-pagetree-alphanum-q-h',                       'svg','alphanum'],
	[$langFile . 'alphabetr',           'alphabetr',            'apps-pagetree-alphanum-r',                         'svg','alphanum'],
	[$langFile . 'alphabetr',           'alphabetr-h',          'apps-pagetree-alphanum-r-h',                       'svg','alphanum'],
	[$langFile . 'alphabets',           'alphabets',            'apps-pagetree-alphanum-s',                         'svg','alphanum'],
	[$langFile . 'alphabets',           'alphabets-h',          'apps-pagetree-alphanum-s-h',                       'svg','alphanum'],
	[$langFile . 'alphabett',           'alphabett',            'apps-pagetree-alphanum-t',                         'svg','alphanum'],
	[$langFile . 'alphabett',           'alphabett-h',          'apps-pagetree-alphanum-t-h',                       'svg','alphanum'],
	[$langFile . 'alphabetu',           'alphabetu',            'apps-pagetree-alphanum-u',                         'svg','alphanum'],
	[$langFile . 'alphabetu',           'alphabetu-h',          'apps-pagetree-alphanum-u-h',                       'svg','alphanum'],
	[$langFile . 'alphabetv',           'alphabetv',            'apps-pagetree-alphanum-v',                         'svg','alphanum'],
	[$langFile . 'alphabetv',           'alphabetv-h',          'apps-pagetree-alphanum-v-h',                       'svg','alphanum'],
	[$langFile . 'alphabetw',           'alphabetw',            'apps-pagetree-alphanum-w',                         'svg','alphanum'],
	[$langFile . 'alphabetw',           'alphabetw-h',          'apps-pagetree-alphanum-w-h',                       'svg','alphanum'],
	[$langFile . 'alphabetx',           'alphabetx',            'apps-pagetree-alphanum-x',                         'svg','alphanum'],
	[$langFile . 'alphabetx',           'alphabetx-h',          'apps-pagetree-alphanum-x-h',                       'svg','alphanum'],
	[$langFile . 'alphabety',           'alphabety',            'apps-pagetree-alphanum-y',                         'svg','alphanum'],
	[$langFile . 'alphabety',           'alphabety-h',          'apps-pagetree-alphanum-y-h',                       'svg','alphanum'],
	[$langFile . 'alphabetz',           'alphabetz',            'apps-pagetree-alphanum-z',                         'svg','alphanum'],
	[$langFile . 'alphabetz',           'alphabetz-h',          'apps-pagetree-alphanum-z-h',                       'svg','alphanum'],
	[$langFile . 'number0',             'number0',              'apps-pagetree-alphanum-0',                         'svg','alphanum'],
	[$langFile . 'number0',             'number0-h',            'apps-pagetree-alphanum-0-h',                       'svg','alphanum'],
	[$langFile . 'number1',             'number1',              'apps-pagetree-alphanum-1',                         'svg','alphanum'],
	[$langFile . 'number1',             'number1-h',            'apps-pagetree-alphanum-1-h',                       'svg','alphanum'],
	[$langFile . 'number2',             'number2',              'apps-pagetree-alphanum-2',                         'svg','alphanum'],
	[$langFile . 'number2',             'number2-h',            'apps-pagetree-alphanum-2-h',                       'svg','alphanum'],
	[$langFile . 'number3',             'number3',              'apps-pagetree-alphanum-3',                         'svg','alphanum'],
	[$langFile . 'number3',             'number3-h',            'apps-pagetree-alphanum-3-h',                       'svg','alphanum'],
	[$langFile . 'number4',             'number4',              'apps-pagetree-alphanum-4',                         'svg','alphanum'],
	[$langFile . 'number4',             'number4-h',            'apps-pagetree-alphanum-4-h',                       'svg','alphanum'],
	[$langFile . 'number5',             'number5',              'apps-pagetree-alphanum-5',                         'svg','alphanum'],
	[$langFile . 'number5',             'number5-h',            'apps-pagetree-alphanum-5-h',                       'svg','alphanum'],
	[$langFile . 'number6',             'number6',              'apps-pagetree-alphanum-6',                         'svg','alphanum'],
	[$langFile . 'number6',             'number6-h',            'apps-pagetree-alphanum-6-h',                       'svg','alphanum'],
	[$langFile . 'number7',             'number7',              'apps-pagetree-alphanum-7',                         'svg','alphanum'],
	[$langFile . 'number7',             'number7-h',            'apps-pagetree-alphanum-7-h',                       'svg','alphanum'],
	[$langFile . 'number8',             'number8',              'apps-pagetree-alphanum-8',                         'svg','alphanum'],
	[$langFile . 'number8',             'number8-h',            'apps-pagetree-alphanum-8-h',                       'svg','alphanum'],
	[$langFile . 'number9',             'number9',              'apps-pagetree-alphanum-9',                         'svg','alphanum'],
	[$langFile . 'number9',             'number9-h',            'apps-pagetree-alphanum-9-h',                       'svg','alphanum']
];
$diplayIconsInBehaviourTab = 0;

$extConf = RtBackendUtility::getExtensionConfiguration('rt_pages_tree_icons');

$diplayIconsInBehaviourTab = $extConf['diplayIconsInBehaviourTab'];

if(version_compare(TYPO3_version, '9.0', '<')) {
	$GLOBALS['TCA']['pages']['columns']['module']['config']['showIconTable'] = $diplayIconsInBehaviourTab;
} elseif(version_compare(TYPO3_version, '9.0', '>=')) {
	$GLOBALS['TCA']['pages']['columns']['module']['config']['fieldWizard']['selectIcons']['disabled'] = !$diplayIconsInBehaviourTab;
}

foreach($pageIcons as $iconsParams) {
	$iP = substr($iconsParams[1], -2);
	if( $iP !== '-s' || $iP !=='-h') {
		$GLOBALS['TCA']['pages']['columns']['module']['config']['items'][] = $iconsParams;
	}
	$GLOBALS['TCA']['pages']['ctrl']['typeicon_classes'][ 'contains-' . $iconsParams[1] ] = $iconsParams[2];
}