conf.py:
  copyright: 2021
  project: Pages Tree Icons
  version: 4.1
  release: 4.1.3
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
  latex_documents:
  - - Index
    - rt_pages_tree_icons.tex
    - A new Backend-Module to have a more comprehensive Page treeview.
    - Regis TEDONE
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Example-ExtensionManual
    github_branch: latest
...
